### ISSUE TITLE
dots (".") in BOT names are not allowed. However, intelmq has many bots with "." in the name

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq-manager#58]
When adding a BOT to the setup in intelmq-manager, a BOT id must not contain a ".".
However, many bots now have a "." in their name. This should be fixed in intelmq-manager, I believe.

**Comment by mauroasilva** [comment]
@aaronkaplan, the PHP already had the correct regex, the javascript was the problem. The latest fix should solve it.

**Comment by aaronkaplan** [comment]
will try.

**Comment by aaronkaplan** [comment]
nope, does not work. Still the same error message: "Bot ID's can only be composed of numbers, letters and hiphens"

**Comment by aaronkaplan** [comment]
sorry, my mistake. works!
